theme.count = 2

# CLASSIC - White / Black / Pink / Blue / Yellow
classic.color.bg        = #FFFFFF
classic.color.fg        = #000000
classic.color.primary   = #FF0097
classic.color.secondary = #0097FF
classic.color.accent    = #FFFF00

# PASTEL
pastel.color.bg        = #D1BFB0
pastel.color.fg        = #392B35
pastel.color.primary   = #BB474F
pastel.color.secondary = #486B7F
pastel.color.accent    = #7A9C96

# Background Dot Theme
theme.dot.spacing = 6
theme.dot.radius = 0.8
