package render;

import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.image.WritableImage;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.scene.paint.Color;
import javafx.scene.paint.ImagePattern;
import utils.config.Config;
import utils.themes.ThemeManager;

/**
 * Utility class for generating theme-aware repeating dot-pattern backgrounds.
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Generate a tiled pixel-art dot pattern based on theme colors</li>
 *     <li>Cache generated backgrounds for performance</li>
 *     <li>Automatically invalidate cached backgrounds when theme changes</li>
 *     <li>Provide a single public API used by the application root</li>
 * </ul>
 *
 * The pattern texture is generated by drawing a single dot in a square tile,
 * then repeating it using an {@link ImagePattern}.
 * The result is used as the background of the main application UI.
 */
public class BackgroundRender {

    // ============================================================
    // Cached background
    // ============================================================

    /** Cached Background instance representing the most recently used dot pattern. */
    private static Background currentBackground;

    /** Cached values used to determine if regeneration is needed. */
    private static int lastSpacing;
    private static double lastRadius;

    // Register theme listener → invalidate cache when theme changes
    static {
        ThemeManager.addListener(BackgroundRender::refreshTheme);
    }


    // ============================================================
    // Theme refresh callback
    // ============================================================

    /**
     * Called automatically whenever the theme changes.
     * <p>
     * Invalidates the cached background so it will be regenerated on next request.
     */
    private static void refreshTheme() {
        currentBackground = null;
    }


    // ============================================================
    // PUBLIC API — get background from config
    // ============================================================

    /**
     * Builds (or retrieves from cache) a dot-pattern background using values
     * from {@link Config}:
     * <ul>
     *     <li><b>theme.dot.spacing</b> — spacing between dots</li>
     *     <li><b>theme.dot.radius</b>  — radius of each dot</li>
     * </ul>
     *
     * @return a JavaFX {@link Background} containing a repeating dot texture
     */
    public static Background dotBackgroundFromConfig() {

        int spacing = Config.getInt("theme.dot.spacing");
        double radius = Config.getDouble("theme.dot.radius");

        // Return cached background if still valid
        if (currentBackground != null &&
                spacing == lastSpacing &&
                radius == lastRadius)
        {
            return currentBackground;
        }

        // Save parameters for caching
        lastSpacing = spacing;
        lastRadius  = radius;

        // Theme colors
        Color dotColor = ThemeManager.get().fg;
        Color bgColor  = ThemeManager.get().bg;

        // Generate background
        currentBackground = dotBackground(spacing, radius, dotColor, bgColor);

        return currentBackground;
    }


    // ============================================================
    // Build repeating dot pattern background
    // ============================================================

    /**
     * Creates a repeating dot-pattern background using the given dimensions
     * and colors.
     *
     * @param spacing    size of each tile (dot spacing)
     * @param dotRadius  radius of the dot
     * @param dotColor   color of the dot
     * @param bgColor    tile background color
     * @return a {@link Background} with a repeated dot texture
     */
    public static Background dotBackground(
            int spacing,
            double dotRadius,
            Color dotColor,
            Color bgColor
    ) {
        Image tile = createDotTile(spacing, dotRadius, dotColor, bgColor);

        ImagePattern pattern = new ImagePattern(
                tile,
                0, 0,
                spacing, spacing,
                false
        );

        return new Background(
                new BackgroundFill(pattern, CornerRadii.EMPTY, javafx.geometry.Insets.EMPTY)
        );
    }


    // ============================================================
    // Create a tile image containing one centered dot
    // ============================================================

    /**
     * Creates a single square tile image containing:
     * <ul>
     *     <li>a solid background of {@code bgColor}</li>
     *     <li>one centered circle (dot) of {@code dotColor}</li>
     * </ul>
     * This tile is later repeated to form the full background.
     *
     * @param size       pixel size of the square tile
     * @param dotRadius  radius of the dot drawn in the center
     * @param dotColor   color used for the dot
     * @param bgColor    background fill color of the tile
     * @return an {@link Image} representing the tile
     */
    private static Image createDotTile(
            int size,
            double dotRadius,
            Color dotColor,
            Color bgColor
    ) {
        Canvas tileCanvas = new Canvas(size, size);
        GraphicsContext gc = tileCanvas.getGraphicsContext2D();

        // Background fill
        gc.setFill(bgColor);
        gc.fillRect(0, 0, size, size);

        // Centered dot
        gc.setFill(dotColor);
        gc.fillOval(
                size / 2.0 - dotRadius,
                size / 2.0 - dotRadius,
                dotRadius * 2,
                dotRadius * 2
        );

        // Capture tile as image
        WritableImage img = new WritableImage(size, size);
        tileCanvas.snapshot(null, img);

        return img;
    }
}
